### ISSUE TITLE
undefined after formatting query

### ISSUE THREAD

**Issue by bart4747** [Trivadis/plsql-formatter-settings#123]
In some cases formater ruins sql query, adding 'undefined'

Sample query

```
SELECT
    mis.segment1, xrctl.*
FROM
    table1      xrct
    JOIN table2 xrctl on xrct.first_id = xrctl.first_id
    join table3 mis on mis.item_id = xrctl.item_id
 LEFT JOIN ( SELECT
    aps.first_id
  , aa.offset_amount / aps.amount_due_original adj_factor
FROM
    (
        SELECT
            first_id
          , SUM(amount)offset_amount
        FROM
            table4
        WHERE
             status = 'A'
            AND reason_code = 'OFFSET'
        GROUP BY
            first_id
    )aa
               JOIN ( SELECT
           first_id
         , SUM(amount_adjusted)    amount_adjusted
         , SUM(amount_due_original)amount_due_original
       FROM
           ar_payment_schedules_all
       HAVING
           SUM(amount_adjusted)<> 0
                      GROUP by first_id)aps ON(aps.first_id = aa.first_id)) adj1 ON xrct.first_id = adj1.first_id
WHERE
        1 = 1
    --    AND xrct.first_id = rct.first_id --'12102600934'
    And xrct.x_number = '12100200739'

        AND xrctl.item_id = 1087533
--HAVING
--    SUM(round(xrctl.extended_amount +(nvl(adj1.adj_factor, 0)* xrctl.extended_amount), 2))<> 0
--group by xrctl.item_id, xrctl.description

```

After CTRL+F7

```
SELECT
    mis.segment1, xrctl.*
FROM
    table1                          xrctundefinedJOIN table2 xrctl on xrct.first_id = xrctl.first_idundefinedjoin table3 mis on mis.item_id = xrctl.item_id
    LEFT JOIN ( SELECTundefined    aps.first_id, aa.offset_amount / aps.amount_due_original adj_factorundefinedFROM(
        SELECT
            first_id, SUM(amount)offset_amount
        FROM
            table4
        WHERE
            status = 'A'
            AND reason_code = 'OFFSET'
        GROUP BY
            first_id
    )aaundefined               JOIN ( SELECTundefined           first_id, SUM(amount_adjusted)amount_adjusted, SUM(amount_due_original)amount_due_original
    FROMundefined           ar_payment_schedules_allundefined       HAVINGundefined           SUM(amount_adjusted)<> 0
                      GROUP
    by first_id)aps ON(aps.first_id = aa.first_id)) adj1 ON xrct.first_id = adj1.first_idundefinedWHEREundefined        1 = 1
    --    AND xrct.first_id = rct.first_id --'12102600934'
    And xrct.x_number = '12100200739'
    AND xrctl.item_id = 1087533
--HAVING
--    SUM(round(xrctl.extended_amount +(nvl(adj1.adj_factor, 0)* xrctl.extended_amount), 2))<> 0
--group by xrctl.item_id, xrctl.description

```

**Comment by PhilippSalvisberg** [comment]
Thanks for reporting this. This looks bad. However, I cannot reproduce it with the default settings and the latest version on the main branch. The result looks like this after calling the formatter:

![image](https://user-images.githubusercontent.com/3883171/127126668-98422d8e-8f47-4a39-9bdd-998d7e380861.png)

And here as code (containing no `undefined`)

```sql
SELECT
    mis.segment1, xrctl.*
FROM
    table1      xrct
    JOIN table2 xrctl on xrct.first_id = xrctl.first_id
    join table3 mis on mis.item_id = xrctl.item_id
 LEFT JOIN ( select aps.first_id,
       aa.offset_amount / aps.amount_due_original adj_factor
               from (
          select first_id,
                 sum(amount) offset_amount
            from table4
           where status = 'A'
             and reason_code = 'OFFSET'
           group by first_id
       ) aa
               JOIN ( select first_id,
                          sum(amount_adjusted) amount_adjusted,
                          sum(amount_due_original) amount_due_original
                        from ar_payment_schedules_all
                      having sum(amount_adjusted) <> 0
                      GROUP by first_id)aps ON(aps.first_id = aa.first_id)) adj1 ON xrct.first_id = adj1.first_id
WHERE
        1 = 1
    --    AND xrct.first_id = rct.first_id --'12102600934'
    And xrct.x_number = '12100200739'

        AND xrctl.item_id = 1087533
--HAVING
--    SUM(round(xrctl.extended_amount +(nvl(adj1.adj_factor, 0)* xrctl.extended_amount), 2))<> 0
--group by xrctl.item_id, xrctl.description
```

Please note, there is a syntax error in the code. `GROUP BY` before the `WHERE` and `HAVING` before `GROUP BY`. The Oracle parser does not understand that and therefore the formatter result is expected to be bad.

However, it should never lead a broken SQL containing `undefined` instead of whitespace.

Which version of the formatter did you use with which settings? Any information that makes the problem reproducible for me would be greatly appreciated.

**Comment by bart4747** [comment]
Please try to format couple times same code, formater keeps adding undefined, 1st time nearly always is ok

![image](https://user-images.githubusercontent.com/51780574/127133671-b271399f-d641-4c2b-bb9f-91ed2f8300a4.png)

I have latest version, issue occurred with such settings

![image](https://user-images.githubusercontent.com/51780574/127134357-13d7dc2a-09ba-47f8-9d21-67e639247366.png)

Without syntax error format works fine.

**Comment by PhilippSalvisberg** [comment]
Ok I used now your settings and I do not get an `undefined` after formatting the code. Result stays the same for subsequent formatter code. Result is:

```sql
SELECT
    mis.segment1, xrctl.*
FROM
    table1      xrct
    JOIN table2 xrctl on xrct.first_id = xrctl.first_id
    join table3 mis on mis.item_id = xrctl.item_id
 LEFT JOIN ( SELECT aps.first_id
  , aa.offset_amount / aps.amount_due_original adj_factor
FROM (
        SELECT
            first_id
          , SUM(amount) offset_amount
        FROM
            table4
        WHERE
            status = 'A'
            AND reason_code = 'OFFSET'
        GROUP BY
            first_id
    ) aa
               JOIN (
    SELECT
        first_id
         , SUM(amount_adjusted)     amount_adjusted
         , SUM(amount_due_original) amount_due_original
       FROM
        ar_payment_schedules_all
       HAVING
        SUM(amount_adjusted) <> 0
                      GROUP by first_id)aps ON(aps.first_id = aa.first_id)) adj1 ON xrct.first_id = adj1.first_id
WHERE
        1 = 1
    --    AND xrct.first_id = rct.first_id --'12102600934'
    And xrct.x_number = '12100200739'

        AND xrctl.item_id = 1087533
--HAVING
--    SUM(round(xrctl.extended_amount +(nvl(adj1.adj_factor, 0)* xrctl.extended_amount), 2))<> 0
--group by xrctl.item_id, xrctl.description
```

Could you please try to use the latest version of the Arbori program in the main branch? - I fixed some issue incompatibilities which might be related. 

I'm using Java 8 in SQLDev:

![image](https://user-images.githubusercontent.com/3883171/127137472-f26e2e0d-8b13-46f3-b10f-13dec403b594.png)

What are you using?

I think I will add a sanity step at the end of the Arbori program to ensure that the calculated indentations do contain whitespaces only. But that's just a safe fail. I'd really like to reproduce this bug and fix the root cause (if it is not already fixed).

Thanks.

**Comment by bart4747** [comment]
![image](https://user-images.githubusercontent.com/51780574/127147758-a8f2fdb0-2722-4318-83c0-5e5fc6c9fdd8.png)
 I use 

Revision: 6265f37c6ad9b5121d57ca8d313226e49d19920a
Author: Philipp Salvisberg <philipp.salvisberg@trivadis.com>
Date: 25.07.2021 21:39:47
Message:
A18: avoid IndexOutOfBoundsException when code ends with comments

**Comment by PhilippSalvisberg** [comment]
Revision looks good. Java Version as well. The settings do not work with SQLDev 20.4, but should work in SQLDev 21.2. However the settings must not break existing code.

I'm still do not understand why I cannot reproduce the behavior. I can imagine what kind of code could produce such a result, but that does not help much. Have to go through all calls...

Nevertheless I will provide a post-processing step that ensures that only whitespaces are placed between tokens. Should be ready later this evening (CET). I'll post an update when it is available.

**Comment by bart4747** [comment]
Maybe this will help you, if you need other information about my settings, don't hesitate to ask.

https://user-images.githubusercontent.com/51780574/127154877-d48c0d3a-c4ea-41a8-9b42-937038d6447c.mp4

**Comment by PhilippSalvisberg** [comment]
I see that this is causing an issue in your environment. I understand that. But I'm unable to reproduce this behavior.

Anyway. I've implemented a fail-safe with commit https://github.com/Trivadis/plsql-formatter-settings/commit/79874e0ee62ce308eef5961ee52e1ca0cc6c1438 .

Please let me know, if this solves your issue. Thank you.

**Comment by PhilippSalvisberg** [comment]
To help me find the root cause of this error, could you please change the default `logging.conf` of the SQLDev installation? 

You find the file in the `user.dir`. In my case it's in `/Applications/SQLDeveloper21.2.0.app/Contents/Resources/sqldeveloper/sqldeveloper/bin` as the following screenshot shows:

![image](https://user-images.githubusercontent.com/3883171/127211732-80d91c3b-e029-4593-8ecb-96ede1d6379f.png)

The default content of `logging.conf` looks like this:

```properties
.level=SEVERE

# Set the default logging level for the root logger
#oracle.level = INFO

# --- ConsoleHandler ---
# Override of global logging level
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
oracle.dbtools.logging.LogPaneHandler.level=ALL
oracle.ide.log.QueuedLoggingHandler.level=OFF
```

You can replace it with this content:

```properties
# handler for console only (will be shown in Messages pane within SQL Developer)
handlers=java.util.logging.ConsoleHandler

# Default global logging level. 
.level=SEVERE

# Loggers
oracle.level=INFO
oracle.dbtools.raptor.config.CustomFormat.level=ALL

# --- ConsoleHandler --- 
java.util.logging.ConsoleHandler.level=ALL
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
java.util.logging.SimpleFormatter.format=%1$tY-%1$tm-%1$td %1$tH:%1$tM:%1$tS %4$s %2$s: %5$s%n
```

and then restart SQL Developer.

You can open the logging window via the `View -> Log` menu option.

When you run the formatter with your example you should get an output similar to the following:

![image](https://user-images.githubusercontent.com/3883171/127212357-5d5e6065-26c5-41bb-96a6-abe1161c65e3.png)

I'm interested in all log lines containing `jdk.nashorn.internal.scripts.Script` (as text, a run starts with `...reset_formatter...` and ends with `...d2_log_time...`). This should help me to determine the reason for the different result in your and my environment.

Thank you.

**Comment by PhilippSalvisberg** [comment]
@bart4747 I've found the bug. Could not reproduce it on macOS but under Windows. Wrong parenthesis caused "undefined" results, but only with Windows specific line separators (CR/LF). 

Latest version on the main branch (5ed4618) should work now.

Thanks for reporting this very nasty bug.
