### ISSUE TITLE
"as" in alias in xml ruins formatting 

### ISSUE THREAD

**Issue by bart4747** [Trivadis/plsql-formatter-settings#144]
Hi,
adding as before alias in xml table query, makes code unformattable.
In addition issue creates formatting errors further down in the code (key words aren't capitalized and white spaces around operators aren't applied )

example below

```sql

SELECT
    lin.source_system

FROM
    XMLTABLE
    (XMLNAMESPACES(DEFAULT 'urn:xxx.com'), '/line'
        PASSING xmltype(p_xml_file)
        COLUMNS
        source_system VARCHAR2(50)PATH './../../source_system'
      , message_id    NUMBER      PATH './../../message_id'
    )lin

  , XMLTABLE
    (XMLNAMESPACES(DEFAULT 'urn:xxx.com'), '/lot'
        PASSING xmltype(p_xml_file)
        COLUMNS
        source_system VARCHAR2(50)PATH './../../../../source_system'
      , message_id    NUMBER      PATH './../../../../message_id'
    )lot
WHERE
    lot.source_system = lin.source_system
    AND lot.message_id = lin.message_id;
```

```sql


SELECT
    lin.source_system

FROM
    XMLTABLE
    (XMLNAMESPACES(DEFAULT 'urn:xxxx'), '/o/line'
        PASSING xmltype(p_xml_file)
        COLUMNS

        source_system VARCHAR2(50)PATH './../../source_system'
      , message_id    NUMBER      PATH './../../message_id')AS a
      , XMLTABLE
    (XMLNAMESPACES(DEFAULT 'urn:xxxx'), '/o/line'
        PASSING xmltype(p_xml_file)
        COLUMNS

                        source_system VARCHAR2(50)PATH './../../source_system'
                      , message_id    NUMBER      PATH './../../message_id')AS b
where a.message_id - b.message_id;

```

**Comment by PhilippSalvisberg** [comment]
You are using undocumented syntax. Here's the relevant syntax diagram from the [Oracle documentation](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6__I2126863):

![image](https://user-images.githubusercontent.com/3883171/134778260-debaac05-3324-43ff-bcdc-46dcc3d9e69d.png)

`AS` is not allowed before [`t_alias`](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/SELECT.html#GUID-CFA006CA-6FF1-4972-821E-6996142A51C6__T_ALIAS-EF134CB8).

The Oracle Database can process it, like in this statement:

```sql
select t.* from xmltable('<root/>') as t ;
```

But IMO this is a bug. Either in the implementation of the parser within the Oracle database (not reporting this syntax error) or in the documentation of the Oracle database (not mentioning the possibility to add `AS` before `t_alias`).

Anyway, the formatter settings are based on the capabilities of the client side parser provided in SQL Developer and SQLcl. And this parser does not understand this syntax. SQLDev reports the syntax error in the code outline, within the editor (red wavy lines) and in the border of the editor with a red marker. 

Since the implementation of issue #135 we do not format code when the client side parser reports errors. Hence this is not a bug of the formatter settings.
