### ISSUE TITLE
Add line break in expression/argument lists with more than 4 arguments

### ISSUE THREAD

**Issue by krokyk** [Trivadis/plsql-formatter-settings#19]
How to achieve this formatting? I.e. same as parameters of a procedure/function
```sql
CREATE OR REPLACE PACKAGE BODY tools AS
    -----------------------------------------
    -- Private functions and procedures START
    -----------------------------------------
    TYPE arr IS
        VARRAY(20) OF VARCHAR2(20) NOT NULL;

    orderable_key_prefixes arr := arr(
        'aaaaaaaaaaaa',
        'bbbbbbbbbbbb',
        'cccccccccccc',
        'dddddddddddd',
        'eeeeeeeeeeee', 
        'ffffffffffff', 
        'gggggggggggg', 
        'hhhhhhhhhhhh', 
        'iiiiiiiiiiii', 
        'jjjjjjjjjjjj', 
        'kkkkkkkkkkkk', 
        'llllllllllll', 
        'mmmmmmmmmmmm'
    );

END;
/
```

When I format I get this:
```sql
CREATE OR REPLACE PACKAGE BODY tools AS
    -----------------------------------------
    -- Private functions and procedures START
    -----------------------------------------
    TYPE arr IS
        VARRAY(20) OF VARCHAR2(20) NOT NULL;
    orderable_key_prefixes arr := arr('aaaaaaaaaaaa', 'bbbbbbbbbbbb', 'cccccccccccc', 'dddddddddddd', 'eeeeeeeeeeee', 'ffffffffffff', 'gggggggggggg', 'hhhhhhhhhhhh', 'iiiiiiiiiiii', 'jjjjjjjjjjjj', 'kkkkkkkkkkkk',
    'llllllllllll', 'mmmmmmmmmmmm');
END;
/
```

**Comment by PhilippSalvisberg** [comment]
By enabling these three lines in the Arbori program.

```
| .breaksProcArgs & [node) arg & [node^) paren_expr_list & [node+1) arg_list     -- salvisberg: disabled, breaks for assoc_args only
| .breaksProcArgs & [node) arg_list & [node^) paren_expr_list & [node-1) arg     -- salvisberg: disabled, breaks for assoc_args only
| .breaksProcArgs & [node) ',' & [node^) arg_list & [node+1) arg                 -- salvisberg: disabled, breaks for assoc_args only
```

This will change the formatting of function parameters as well. I've disabled these lines, because I thought that if you want to have line breaks, then you should use the named notation as suggested by [G-7110](https://trivadis.github.io/plsql-and-sql-coding-guidelines/v3.6/4-language-usage/7-stored-objects/1-general/g-7110/). So I like to have 

```
xyz := to_char(x, 'DD.MM.YYYY');
```` 

On a single line. I do not like this result:

```
xyz  := to_char(
    x,
    'DD.MM.YYYY'
);
```

You see, fixing one problem is usually easy. But taking the all cases into account makes it more difficult. ;-)

I hope this answers your question.

**Comment by krokyk** [comment]
I understand, you fix your sink and realize your chimney fell down :)

Anyway, I noticed in Toad for Oracle, they have that neat feature where you can configure wrapping of the parameters based on their count. So let's say I can accept having 4 params on 1 line (in proc call or in my case in array definition) but I would like to break them on separate lines if there are 5 or more or the line length exceeds the threshold.

Would that be a (viable) option?

**Comment by PhilippSalvisberg** [comment]
Yes, this is doable.

**Comment by jgebal** [comment]
I wonder if number of arguments is the best possible condition to switch formatting form in-line to multi-line.
Wouldn't it be better to use margin settings or expression(argument list) length?

**Comment by PhilippSalvisberg** [comment]
@jgebal yes, you are right. But calculating the correct positions for the token during the formatting is not simple. You would need to do that at the very end. For correct results, iteratively. It's more than adding just a new line. For example It impacts the comma handling and indentation. I decided to go with the number of arguments, because it is much simpler.

**Comment by jgebal** [comment]
formatting code  is amazingly complex especially with SQL and it's rich vocabulary and versatility of optional items.
I truly admire what you're doing.

**Comment by PhilippSalvisberg** [comment]
Thanks @jgebal. I do not think it is that complicated. The problem is that there are a lot of unit tests missing. I've started to create some for each change. But I have basically no idea what the side effects of a change are. So I try to format some of my code and I see a lot of cases that are not handled they way I would like it. Then I check if it was the case before and if yes, then I keep it that way. So it's you and others such as @krokyk that drive the change by creating issues. I'm still thinking about how to proceed to get a more complete set of unit tests. All options lead to a lot of work... 

Regarding this case. I'm not happy with counting arguments. I found a case where 6 short parameters are passed (creating an object type) that would easily fit on line, but are splitted now. So maybe an imperfect counting mechanism, such as counting the content of an argument and considering let's say 70% of the configured line size as a limit would be better.

**Comment by PhilippSalvisberg** [comment]
>(1) Make number of arguments/expressions configurable

Configuration is the "Advanced Formatting" section. That's it. There is one similar parameter. It is named "Line Breaks: Commas per line in procedure" (1 comma means two arguments). We are currently not using this parameter in a consistent way.

Another option is to create an own formatter extension with dedicated formatting preferences. This makes sense when Arbori is not enough and some post-processing is necessary. However, this would require an additional context menu entry. Such as "Beautify" or "Custom Format" or similar. Making this compatible with SQLcl will become more difficult. So this is really the last resort and we'd like to avoid it. So the settings can be configured with what is available in "Advanced Formatting". Everything else will be hard-coded. We choose the value we like most ;-)

>(2) Second - if the margin is exceeded

As explained previously, calculating the exact number of characters used by all tokens on the line can happen after formatting only. However, an estimation is possible and in combination with a safety margin (e.g. 70%) this is doable and will lead most probably to better results than the current implementation (3).

Arbori gets the full parse-tree and has access to all the args and its length. I know how to query them. I'd consider the length plus 1 or 2 chars per arg for parenthesis, comma and space between args. So getting the total chars of all args is doable. The challenge is to define the max. number of chars allowed before splitting args. For that we would need the tokens before the argument list. At that time not all formatting steps are completed, so we cannot reliably calculate the line size. We have to estimate it and define a safety margin. A percentage somehow related with the line size (it matters if it is 40 vs. 70 vs. 200 vs. 400). This needs some more thinking. But whatever we choose will not be perfect. There will be cases where the post-processor of SQLDev will identify a line which is longer than the max and it will add a line break plus an indentation of the previous line before a token. And of course there will be other cases where everything would fit into a line but we are splitting it. The latter is better IMO, because we control the formatting result.

>(3) If more than X arguments, split arguments 1 per line

I would not combine (2) and (3). It's either (2) or (3). Doing (2) right should lead to a better result. Probably only corner cases could produce a better result.

**Comment by krokyk** [comment]
I was not suggesting combining 2 & 3, it's more like if-else if.
```java
if margin_exceeded {
    //split each arg into its own line
} else if num_args > 4 {
    //split each arg into its own line
} else {
    //do nothing
}
```

**Comment by PhilippSalvisberg** [comment]
Well, I was suggesting something like this:

```
if margin_exceeds {
   // split, each arg on own line
} else {
   // do nothing
}
```

I really thing the result will be better and the solution will be simpler.
