### ISSUE TITLE
SQL Dev: Doubled blank lines before comments 

### ISSUE THREAD

**Issue by markushohloch** [Trivadis/plsql-formatter-settings#2]
Hi Philipp,

thanks for your great blog and sharing your code on SQL Developer formatting. 

I have an issue with this configuration. All blank lines before comments will be doubled after formatting. 
Example:
```
CREATE OR REPLACE PACKAGE test_formatting AS


   /* Tow line before this comment will result in four lines */
   FUNCTION foo (
      p_bar VARCHAR2
   ) RETURN NUMBER;

END test_formatting;
```

After format I got this result:
```
CREATE OR REPLACE PACKAGE test_formatting AS




   /* Tow line before this comment will result in four lines */
   FUNCTION foo (
      p_bar VARCHAR2
   ) RETURN NUMBER;

END test_formatting;
```

I tried this with SQL Developer 19.4 (64-bit, Java 1.8.0_221) on Windows 10.

Regards,
Markus

**Comment by PhilippSalvisberg** [comment]
Thanks @markushohloch for reporting this issue. Could you please provide a little example? Thank you.

**Comment by PhilippSalvisberg** [comment]
Ok, I can reproduce it.

```
select * from dual;

-- test comment
select * from dual;
````

First format result under macOS. I can repeat formatting it. Result stays the same.
```
select * from dual;

-- test comment
select * from dual;
```

First format result under Windows:
```
SELECT *
  FROM dual;


-- test comment
SELECT *
  FROM dual;
```

Second format result under Windows:
```
SELECT *
  FROM dual;




-- test comment
SELECT *
  FROM dual;
```

I guess the problem is the preference `Line breaks` -> `After statements` -> `Preserve original`.

Obviously `Preserve original` does not work on any platform. I tried to change it to `Single break`. This seams to work. 

However, the behavior is still strange (this time on macOS where the number of lines is reduced by every formatter call until it's just one empty line. I consider this a bug of the formatter Java class and not of the Arbori program. So we have to inform the SQL Developer team to fix that.

**Comment by PhilippSalvisberg** [comment]
I checked with default settings.  For  `Line breaks` -> `After statements` -> `Double break`. This works differently under Windows and macOS as well.

Adding "spaces" an empty lines changes the behavior as well. Really strange. 

Using `Single break` or `Double break` seems to be the only feasible workaround for the time being.

**Comment by markushohloch** [comment]
Ok, thank you very much for your quick response. I can ask the SQL Developer Team if they can take a look at it.

**Comment by PhilippSalvisberg** [comment]
Yes, please. Could you also post the link here? Thanks a lot.

**Comment by markushohloch** [comment]
You're welcome. [https://twitter.com/MarkusHohloch/status/1250110284032806919](https://twitter.com/MarkusHohloch/status/1250110284032806919)

**Comment by markushohloch** [comment]
https://community.oracle.com/message/15597056#15597056
