### ISSUE TITLE
Create table / create tablespace not formatting properly

### ISSUE THREAD

**Issue by jhult** [Trivadis/plsql-formatter-settings#211]
Using [trivadis_custom_format.arbori](https://raw.githubusercontent.com/Trivadis/plsql-formatter-settings/e01b24b90aa7693d5e0c56ff11bac6dfcb2ce179/settings/sql_developer/trivadis_custom_format.arbori) inside Oracle SQLDeveloper (Version 21.4.3.063 Build 063.0100)

Before:

```
CREATE TABLE configuration (id NUMBER NOT NULL);

CREATE TABLESPACE my_table_space DATAFILE 'my_tablespace_file.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
```

After:

```
CREATE TABLE configuration (id NUMBER NOT NULL);

CREATE TABLESPACE my_table_space DATAFILE 'my_tablespace_file.dbf' SIZE 50M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT
MANAGEMENT LOCAL AUTOALLOCATE;
```

Expected:

```
CREATE TABLE configuration (
   id NUMBER NOT NULL
);

CREATE TABLESPACE my_table_space
   DATAFILE 'my_tablespace_file.dbf' SIZE 50M
   AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
   EXTENT MANAGEMENT LOCAL AUTOALLOCATE;
```

I get the same results when using the standalone formatter.

If I use the default arbori that ships with SQLDeveloper, it formats properly (matches Expected above). This works both inside SQLDeveloper and with the standalone formatter.

**Comment by PhilippSalvisberg** [comment]
Thank you for taking the time to report this issue.

This is an expected behavior.

The Arbori program implements a [lightweight formatter](https://github.com/Trivadis/plsql-formatter-settings#lightweight-formatter). As explained in the [related blog post](https://www.salvis.com/blog/2021/07/18/lightweight-formatter-for-pl-sql-sql/) it basically covers only the following SQL statements

- `create function`
- `create package`
- `create package body`
- `create procedure`
- `create trigger`
- `create type`
- `create type body`
- `create view`
- `delete`
- `insert`
- `merge`
- `select`
- `update`

Other statements are kept "as is" (beside some common processing like adding a line break after reaching the max. line size, changing case of keywords/identifiers).

However, with the implementation of #134 we cover also the `select` part of an `create materialized view` statement. 

We should amend the README and document this limitation and not only in the [related blog post](https://www.salvis.com/blog/2021/07/18/lightweight-formatter-for-pl-sql-sql/).

**Comment by jhult** [comment]
Thanks for the fast response. Sorry for missing the blog post.

It seems like formatting for `create tablespace` was at least partially added here: https://github.com/Trivadis/plsql-formatter-settings/issues/26 / https://github.com/Trivadis/plsql-formatter-settings/pull/35

**Comment by PhilippSalvisberg** [comment]
> Thanks for the fast response. Sorry for missing the blog post.

No problem. I'll change the README based on this ticket.

> It seems like formatting for `create tablespace` was at least partially added here: #26 / #35

Yes. That's right. Back then it was a fork of the default Arbori program. It became quickly unmaintainable. This was the reason for #105, released on [15-July-2021](https://github.com/Trivadis/plsql-formatter-settings/releases/tag/sqlcl-21.1.0-light).
