### ISSUE TITLE
Superb Script

### ISSUE THREAD

**Issue by venkatbollu1212** [Trivadis/plsql-formatter-settings#248]
@PhilippSalvisberg Thanks for the script, this is awesome. I found just one issue with this script even if I use the same script.. 

Say we have a small code snippet like this
```
CREATE OR replace PACKAGE ABC
IS
    k_pkg_name CONSTANT VARCHAR2(30) := $$PLSQL_UNIT;
    g_id NUMBER;
    g_sender       VARCHAR2(100) := k_pkg_name || '@gmail.com';
BEGIN
    NULL;
END;

```
It is working as expected converting the case but when you look at those global variables, the formatter adds one empty line in between.

```
CREATE OR REPLACE PACKAGE ABC IS

    k_pkg_name CONSTANT VARCHAR2(30) := $$PLSQL_UNIT;

    g_id     NUMBER;

    g_sender VARCHAR2(100) := k_pkg_name || '@gmail.com';

BEGIN
    NULL;
END;

```
Any suggestion on how to fix this? Also attaching my tweaked file formatter.br for your reference.

[Formatter.zip](https://github.com/Trivadis/plsql-formatter-settings/files/11166704/Formatter.zip)

Appreciate your response and solution.

Thanks a ton
Venkat

**Comment by PhilippSalvisberg** [comment]
So you are using PL/SQL Developer, right? So when you are using [these settings](https://github.com/Trivadis/plsql-formatter-settings/blob/main/settings/plsql_developer/trivadis_beautifier.br) no empty lines are created. Your settings produce this unwanted result.

The reason is the line

```
EmptyLines=0
```

The meaning is
- `0` remove empty lines. 
- `1` merge empty lines into one.
- `2` preserve empty lines.

Change it back to `1`. In the UI preferences, it corresponds to this:

![image](https://user-images.githubusercontent.com/3883171/230307667-c30c1581-1670-4cc3-9e54-c01a5177f11c.png)

Then no empty lines should be generated.

IMO it's a bug in PL/SQL Developer. Please contact Allround Automations directly. Thank you.

I close this issue since it is not related to the provided preferences in this repo.

**Comment by venkatbollu1212** [comment]
Thanks for your prompt response, I will see what can be done.
