### ISSUE TITLE
Function header formatting: return deterministic

### ISSUE THREAD

**Issue by Gepar** [Trivadis/plsql-formatter-settings#250]
I think no need to add new line after return and before ; in function header
Before:
<img width="597" alt="image" src="https://user-images.githubusercontent.com/5103892/231093848-1477cd40-0383-41e0-8094-dc5bfbae5235.png">
After
<img width="432" alt="image" src="https://user-images.githubusercontent.com/5103892/231093953-9677501c-c7cb-4843-94f2-68d4a0166d8c.png">
I think better to keep _deterministic_ after return on same line.
For me it's hard to search by _return_ keyword in abori file to try to fix it by myself.

**Comment by PhilippSalvisberg** [comment]
In this case I consider the line break as OK. Please note that the Arbori program implements [lightweight formatted](https://github.com/Trivadis/plsql-formatter-settings#lightweight-formatter). As a result 

this single line input

```sql
create or replace package util is function shift(str clob,n pls_integer:=2) return clob deterministic;end;
```

produces this output:

```sql
create or replace package util is
   function shift(str clob,
                  n   pls_integer := 2) return clob
      deterministic;
end;
```

and this input where almost every token is on a new line:

```sql
create 
or
replace
package
util
is
function
shift
(
str
clob
,
n
pls_integer
:=2
)
return
clob
deterministic
;
end
;
```

produces this output:

```sql
create or replace package util
is
   function shift(
      str clob,
      n   pls_integer := 2
   )
      return clob
      deterministic;
end;
```

You see the results are different. This allows some flexibility. However, `deterministic` is always put on a new line. The only option you can enforce your formatting style is something like this:

```sql
create or replace package util is
   function shift(str clob, --@formatter:off
                  n   pls_integer := 2) return clob deterministic; --@formatter:on
end;
```

We do not plan to change this behaviour. Why? Because we have to deal with all language features. In this case with the other options in a [function_declaration](https://github.com/Trivadis/plsql-formatter-settings#lightweight-formatter).

This is also why you do not find `deterministic` in the Arbori program.  It's handled the same way for all options. If you want to change the behaviour in your own fork, you should search for `subprg_property` instead.
