### ISSUE TITLE
compiler flag concatenated to same line as end statement

### ISSUE THREAD

**Issue by Samccull-Bunnings** [Trivadis/plsql-formatter-settings#258]
The compiler flags are not following the same standard as other plsql, the below code has put the flag on the same line as the end of the package

![image](https://github.com/Trivadis/plsql-formatter-settings/assets/94417348/c6c8d87e-5fec-4eb4-a293-756b32fafa38)
becomes
![image](https://github.com/Trivadis/plsql-formatter-settings/assets/94417348/c4999450-c0a5-42e2-bbab-e0d445bfa7b3)

(text copy attached for reference)
[test.txt](https://github.com/Trivadis/plsql-formatter-settings/files/13608546/test.txt)

**Comment by PhilippSalvisberg** [comment]
I use the current Formatter Setter settings in this repo (`trivadis_advanced_format.xml` and `trivadis_advanced_format.xml`) with SQL Developer 23.1 on macOS to format the following code:

```sql
create or replace package test_package as
$if false $then
--code
$end 
end test_package;
/
```

The formatter result looks the same as the input.

Could you please provide me the settings you've changed to reproduce your formatting result?

**Comment by PhilippSalvisberg** [comment]
Similar to #257 this issue is only reproducible with the standard Arbori program provided by the SQL Developer team. It cannot be reproduced with the formatter settings provided in this repository. As a result, I kindly ask you to seek help in the SQL Developer forum regarding common SQL Developer issues. Thank you.
