### ISSUE TITLE
X2 breaks at some (unwanted) places

### ISSUE THREAD

**Issue by krokyk** [Trivadis/plsql-formatter-settings#34]
Hi,

why are 2 line breaks added after some statements and not after others? They all seem equal to me.

1. after the 1st println
2. after the first l_new_ordering :=...

but after that no breaks after either of those. As to what I would like to achieve is having no double breaks there. I am still using the X2 setting because I want empty lines between proc/func declarations/definitions.

I would happily switch to X1 breaks if somehow those empty lines between individual procs/funcs were preserved (can you point me to the relevant arbori part?) or even preserve original (but we know that doesn't really work well as some unwanted indentation and whatnot is added to some lines after each performed formatting)

```sql
BEGIN
    FOR c_ord IN (
        SELECT *
          FROM configuration_ordering
         WHERE REGEXP_LIKE ( ordering,
                             fmt('(^%s$|^%s,.+$|^.+,%s,.+$|^.+,%s$)', p_id, p_id, p_id, p_id) )
         ORDER BY scope
    ) LOOP
        BEGIN
            println('    Removing id from ordering for %s, scope=%s, owner=%s... ', c_ord.key_prefix, son(c_ord.scope), son(c_ord.owner));

            l_new_ordering := REGEXP_REPLACE(c_ord.ordering, fmt('^%s$', l_id), NULL);

            l_new_ordering := REGEXP_REPLACE(l_new_ordering, fmt('^%s,(.+)$', l_id), '\1');
            l_new_ordering := REGEXP_REPLACE(l_new_ordering, fmt('^(.+),%s,(.+)$', l_id), '\1,\2');
            l_new_ordering := REGEXP_REPLACE(l_new_ordering, fmt('^(.+),%s$', l_id), '\1');
            println('    OLD:%s', son(c_ord.ordering));
            println('    NEW:%s', son(l_new_ordering));

            -- UPDATE configuration_ordering
            --    SET ordering = l_new_ordering
            --  WHERE id = c_ordering.id;

            dbms_output.put_line('OK');
        EXCEPTION
            WHEN OTHERS THEN
                dbms_output.put_line('FAILED');
                RAISE;
        END;
    END LOOP;
END delete_from_ordering;
```

My settings:
![image](https://user-images.githubusercontent.com/15148711/89631381-0137f480-d8a1-11ea-8f43-a3e67236edf3.png)

**Comment by PhilippSalvisberg** [comment]
>I would happily switch to X1 breaks if somehow those empty lines between individual procs/funcs were preserved (can you point me to the relevant arbori part?) or even preserve original (but we know that doesn't really work well as some unwanted indentation and whatnot is added to some lines after each performed formatting)

You have asked a similar question in #25. See paragraph "Empty Lines" in https://github.com/Trivadis/plsql-formatter-settings/issues/25#issuecomment-667973637 .

**Comment by krokyk** [comment]
> You have asked a similar question in #25. See paragraph "Empty Lines" in #25 (comment) .

Don't think it similar. I am puzzled because at one time there are 2 breaks after `println` and 2 other times within the same block on the same level just one break (and same for the assignment line `l_new_ordering := `)

**Comment by PhilippSalvisberg** [comment]
You asked:

>why are 2 line breaks added after some statements and not after others? 

In the referred comment I explained how significant statement are identified. And mentioned the `brkX2_1` query. And this query is responsible that some `println` statements lead to an empty line and some not. You can easily check that yourself. 

First of all simplify the test case to something like

```
BEGIN
   println('    Removing id from ordering for %s, scope=%s, owner=%s... ', c_ord.key_prefix, son(c_ord.scope), son(c_ord.owner));
   println('    OLD:%s', son(c_ord.ordering));
   println('    NEW:%s', son(l_new_ordering));
END;
```

paste it into a SQLDev worksheet. Format it and enable the outline and then in the outline window start the Arbori editor. Then paste the [`brkX2_1` query](https://github.com/Trivadis/plsql-formatter-settings/blob/8f9572dcc188cfd4af154aa90fbbaede05c2f0b2/settings/sql_developer/trivadis_custom_format.arbori#L846-L856) into the Arbori editor.

Since version 20.2 at least one query in the editor requires a "->" (even if no callback is called). Add this to the query and execute it. Then you get two result result rows. One for the complete block and one for the first `println`. At this time your SQLDev editor should look like this:

![image](https://user-images.githubusercontent.com/3883171/89672909-bf7d6d00-d8e5-11ea-8a46-5235be2a4dac.png)

This part of the code is really responsible to identify the significant statements.

Now look at the Arbori program. One query criterion must be responsible for this "dynamic" behaviour. In other words why only the first `println` is considered significant. Can you spot it? It contains an `18`. ;-)

Sorry, but this two questions a very very similar.
